# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kKmm3xNu8FYANcIkl9VaFOlZhRkBegNn
"""

# ÉTAPE 1 : INSTALLER LES LIBRAIRES
!pip install yfinance pandas plotly -q

# ÉTAPE 2 : MONTER GOOGLE DRIVE (pour sauvegarder les données)
from google.colab import drive
drive.mount('/content/drive')

# ÉTAPE 3 : COLLECTER LES DONNÉES DE PLUSIEURS ACTIONS
import yfinance as yf
import pandas as pd
from datetime import datetime

# Liste d'actions à collecter
symbols = ["AAPL", "TSLA", "MSFT", "BTC-USD", "GOOGL"]

# Dossier où sauvegarder
save_path = "/content/drive/MyDrive/stock_data"
!mkdir -p "$save_path"

all_data = []

print("Collecte en cours...")
for symbol in symbols:
    print(f"  → {symbol}")
    ticker = yf.Ticker(symbol)
    df = ticker.history(period="1y")
    df = df.reset_index()
    df['symbol'] = symbol
    df['date'] = df['Date'].dt.strftime('%Y-%m-%d')
    df = df[['date', 'Open', 'High', 'Low', 'Close', 'Volume', 'symbol']]
    all_data.append(df)

    # Sauvegarde chaque action en CSV
    df.to_csv(f"{save_path}/{symbol}.csv", index=False)

# Fusionner tout
full_df = pd.concat(all_data)
full_df.to_csv(f"{save_path}/ALL_STOCKS.csv", index=False)

print(f"\nTOUTES LES DONNÉES SAUVEGARDÉES DANS GOOGLE DRIVE !")
print(f"Chemin : {save_path}")
print(f"Total : {len(full_df)} lignes")

# ÉTAPE 4 : VISUALISATION INTERACTIVE (CORRIGÉE)
import pandas as pd
import plotly.express as px

# Chemin CORRIGÉ (sans faute)
save_path = "/content/drive/MyDrive/stock_data"

# Charger le bon fichier
df = pd.read_csv(f"{save_path}/ALL_STOCKS.csv")  # ← C'EST ÇA LE BON NOM !

# Graphique
fig = px.line(df, x='date', y='Close', color='symbol', title="Évolution des prix (1 an)")
fig.update_xaxes(title="Date")
fig.update_yaxes(title="Prix de clôture ($)")
fig.show()

print("Graphique affiché !")

# VOIR LES DONNÉES COMME UN TABLEAU PRO
import pandas as pd

# Charger toutes les données
df = pd.read_csv(f"{save_path}/ALL_STOCKS.csv")

# Afficher les 10 dernières lignes
print("10 DERNIÈRES LIGNES DE DONNÉES :")
display(df.tail(10))

# Statistiques rapides
print("\nSTATISTIQUES PAR ACTION :")
print(df.groupby('symbol')['Close'].agg(['min', 'max', 'mean']).round(2))

# ÉTAPE 6 : INSTALLER ET UTILISER TIINGO (NOUVELLE SOURCE DE DONNÉES)
!pip install tiingo -q

from tiingo import TiingoClient
import pandas as pd
from datetime import datetime

# ← REMPLACE PAR TA CLÉ API TIINGO !
TIINGO_API_KEY = "fefa4effbf074c2283ce9d587dffb96a859f2a19"  # Ex: "a1b2c3d4e5f6g7h8i9j0"

# Config
config = {'api_key': TIINGO_API_KEY, 'session': True}
client = TiingoClient(config)

# Actions à extraire (mêmes que avant)
symbols = ["AAPL", "TSLA", "MSFT", "GOOGL"]  # BTC pas supporté par Tiingo

save_path = "/content/drive/MyDrive/stock_data"
tiingo_path = f"{save_path}/tiingo_data"
!mkdir -p "$tiingo_path"

print("Extraction Tiingo en cours...")

for symbol in symbols:
    print(f"  → {symbol}")

    # 1. EXTRAIRE PRIX OHLCV (1 an)
    try:
        end_date = datetime.now()
        start_date = end_date.replace(year=end_date.year - 1)
        df_prices = client.get_dataframe(symbol, startDate=start_date, endDate=end_date, frequency='daily')
        df_prices = df_prices.reset_index()
        df_prices['symbol'] = symbol
        df_prices['source'] = 'tiingo'
        df_prices = df_prices[['date', 'open', 'high', 'low', 'close', 'volume', 'symbol', 'source']]
        df_prices.columns = ['date', 'Open', 'High', 'Low', 'Close', 'Volume', 'symbol', 'source']  # Uniformiser
        df_prices.to_csv(f"{tiingo_path}/{symbol}_prices.csv", index=False)
        print(f"     Prix sauvés : {len(df_prices)} lignes")
    except Exception as e:
        print(f"     Erreur prix {symbol}: {e}")

    # 2. EXTRAIRE NEWS (derniers 30 jours, top 5)
    try:
        news = client.get_ticker_news(symbol, limit=5, startDate=datetime.now().replace(days=-30))
        news_df = pd.DataFrame(news)
        news_df['symbol'] = symbol
        news_df['source'] = 'tiingo'
        news_df.to_csv(f"{tiingo_path}/{symbol}_news.csv", index=False)
        print(f"     News sauvées : {len(news_df)} articles")
    except Exception as e:
        print(f"     Erreur news {symbol}: {e}")

# Sauvegarder TOUS les prix Tiingo en un fichier
all_tiingo_prices = []
for symbol in symbols:
    df = pd.read_csv(f"{tiingo_path}/{symbol}_prices.csv")
    all_tiingo_prices.append(df)
full_tiingo = pd.concat(all_tiingo_prices)
full_tiingo.to_csv(f"{tiingo_path}/ALL_TIINGO_PRICES.csv", index=False)

print(f"\n🎉 TOUT SAUVÉ DANS : {tiingo_path}")
print("Vérifie Google Drive → stock_data → tiingo_data")