name: Run Analysis

on:
  schedule:
    - cron: '0 18 * * 1-5'
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install
      run: |
        pip install yfinance pandas numpy requests
        pip install torch --index-url https://download.pytorch.org/whl/cpu
        pip install transformers
    
    - name: Run scripts
      run: |
        python data_pipeline.py
        NEWSAPI_KEY="ed172154b55e4d4eb95db4ac7895b29e" \
        GNEWS_API_KEY="7fd1230f54a4be2030c483514e145263" \
        python sentiment_analysis.py
